language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add rustfmt --toolchain=nightly
  - rustup component add clippy

script: |
  cargo fmt    -- --write-mode=diff &&
  cargo clippy -- -D warnings &&
  cargo build  --verbose &&
  cargo test   --verbose
