on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/workflows/deploy_docs.yml"
  pull_request:

name: Continuous integration

jobs:
  check:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pypy
        uses: actions/setup-python@v3
        with:
          python-version: "pypy-3.9"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-14.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - uses: Swatinem/rust-cache@v1
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: lint
          args: -- -D warnings
      - name: test.py
        run: |
          pypy ./test.py -d ./tests --always-build
          pypy ./test.py -d ./examples --always-build
        shell: bash

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
