on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/deploy_docs.yml"

name: Deploy docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Swatinem/rust-cache@v1
      - name: Install mdbook
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook --no-default-features --features search --vers "^0.4" --locked
      - name: Build docs
        run: |
          cd docs
          mdbook build
      - name: Publish HTML
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
